version: 2
jobs:
  build:
     working_directory: /var/www
     docker:
        - image: retreatguru/php56-apache
          environment:
            WORDPRESS_DB_HOST: 127.0.0.1
            WORDPRESS_DB_NAME: rgconnect
            WORDPRESS_DB_USER: wp
            WORDPRESS_DB_PASSWORD: wp

        - image: mysql:5.7
          environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: rgconnect
            MYSQL_USER: wp
            MYSQL_PASSWORD: wp

     steps:
        - run:
            name: Pre-checkout
            command: |
              rm -rf /var/www/html
              echo '127.0.0.1 rgconnect.dev' >> /etc/hosts

        - checkout

        - run:
            name: Build
            command: |
              cp .env.default .env
              composer install -d programs-remote-tests/
              mkdir /var/www/html
              chown noroot:www-data /var/www/html
              su noroot -c 'cd /var/www/html && ../docker/bin/configure-wordpress.sh'

        - run:
            name: Start web server
            command: service apache2 start

        - run:
            name: Test
            command: |
              cd /var/www/programs-remote-tests
              vendor/bin/codecept run acceptance

        - store_artifacts:
            path: /var/www/programs-remote-tests/tests/_output
