#!/bin/bash

main() {
    case $1 in
        up)
            build
            ;;
        down)
            docker-compose down
            ;;
        shell)
            docker-compose exec wordpress bash
            ;;
        debug)
            shift
            if [ ! "$1" ]; then
                echo "usage $0 debug <on|off>"
                exit 1
            fi
            HOST=$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | head -1 | awk '{print $2}')
            docker-compose exec wordpress xdebug.sh $1 $HOST 9000
            docker-compose restart wordpress
            ;;
        *)
            cat <<EOF
Development Environment Manager

Usage: $0 <command> [options]

The following commands are supported:

up       Start development environment (builds if necessary)
down     Destroy development environment (also clears the DB)
shell    Enter wordpress container shell
debug    Turn debugging (xdebug) on or off
EOF
            exit 1
            ;;
    esac
}

# run a wp-cli command
wp() {
    docker-compose exec wordpress wp --allow-root "$@"
}

# build wordpress and link in the theme
build() {
    # set up the theme using symbolic links
    mkdir -p html/wp-content/plugins
    cd html/wp-content/plugins/
    ln -fs ../../../programs-* .
    cd - > /dev/null

    # start containers and wait for DB
    docker-compose up --build -d
    docker-compose exec wordpress wait-db.sh
    docker-compose exec --user=noroot wordpress composer install -d ../programs-remote-tests

    # install wordpress
    wp core download
    wp config create --dbname=rgconnect --dbuser=wp --dbpass=wp --dbhost=db
    wp db reset --yes
    wp core install \
        --url=rgconnect.dev \
        --title="RG Connect Site" \
        --admin_email=info@retreat.guru \
        --admin_user=admin \
        --admin_password=admin \
        --skip-email
    wp plugin activate programs-remote-listings
    wp post delete 1 # hello world

    wp rewrite structure /%postname%/
    wp post create --post_type=page --post_title='Events' --post_status=publish
    wp post create --post_type=page --post_title='Teachers' --post_status=publish

    # Seed another pair of pages for testing
    wp post create --post_type=page --post_title='Retreats' --post_status=publish
    wp post create --post_type=page --post_title='Gurus' --post_status=publish

    # Seed shortcode pages for testing
    wp post create --post_type=page --post_title='Shortcode Event List' --post_status=publish --post_content="[rs_programs category='plant-medicine']"
    wp post create --post_type=page --post_title='Shortcode Event List Table' --post_status=publish --post_content="[rs_programs table show_title show_register_link show_date show_price_first show_more_link show_availability show_availability_words]"
    wp post create --post_type=page --post_title='Shortcode Teachers' --post_status=publish --post_content="[rs_teachers]"
    wp post create --post_type=page --post_title='Shortcode Event List Hide Text' --post_status=publish --post_content="[rs_programs hide_text]"
    wp post create --post_type=page --post_title='Shortcode Event List Hide Location' --post_status=publish --post_content="[rs_programs hide_location]"
    wp post create --post_type=page --post_title='Shortcode Event List Table Less' --post_status=publish --post_content="[rs_programs table show_title show_date]"
    wp post create --post_type=page --post_title='Shortcode Event List Table by Category' --post_status=publish --post_content="[rs_programs table show_title show_date category='plant-medicine']"
    echo "Remember to add rgconnect.dev to your /etc/hosts file"
}

main "$@"